package com.sai.sports.analyzer

import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File
import java.util.Locale

/**
 * Exports canonical pose sequences plus the scores this implementation produces
 * for them, for the backend's parity test to check itself against.
 *
 * ## Why this exists
 *
 * The server auto-flags a submission when its score disagrees with the device's.
 * That mechanism is what makes results trustworthy — and it is also what breaks
 * first if the Kotlin and Python scorers drift apart. When they drift, the flag
 * fires on honest athletes, and the reviewer looking at the flag has no way to
 * tell a real discrepancy from an implementation gap.
 *
 * Two implementations of the same algorithm in two languages will drift. The
 * only question is whether anyone finds out before an athlete does. So this
 * test writes the sequences and the expected answers to a shared directory, and
 * `backend/tests/test_parity.py` asserts the Python port agrees.
 *
 * Fixtures are committed, so the backend suite does not depend on a Gradle run.
 * Regenerate after any threshold or algorithm change:
 *
 *     gradlew :app:testDebugUnitTest --tests "*ParityFixtureExportTest*"
 */
class ParityFixtureExportTest {

    private val outputDirectory = File(FIXTURE_DIRECTORY)

    @Test
    fun `export canonical fixtures and expected scores`() {

        outputDirectory.mkdirs()

        val manifest = StringBuilder()
        manifest.append("# Generated by ParityFixtureExportTest.kt — do not edit by hand.\n")
        manifest.append("# The backend's test_parity.py asserts the Python port reproduces these.\n")
        manifest.append("sequence,test,athlete_height_cm,expected_score,expected_status\n")

        cases().forEach { case ->

            File(outputDirectory, case.fileName).writeText(
                PoseSequenceCodec.encode(case.frames, case.testType.displayName)
            )

            val analyzer: TestAnalyzer = when (case.testType) {
                TestType.SIT_UPS -> SitUpAnalyzer()
                TestType.VERTICAL_JUMP -> VerticalJumpAnalyzer(case.athleteHeightCm!!)
            }

            val result = analyzer.analyzeSequence(case.frames)

            manifest.append(case.fileName).append(',')
            manifest.append(case.testType.name).append(',')
            manifest.append(case.athleteHeightCm?.let { format(it) } ?: "").append(',')
            manifest.append(format(result.score)).append(',')
            manifest.append(result.status.name).append('\n')
        }

        File(outputDirectory, MANIFEST_NAME).writeText(manifest.toString())

        assertTrue(
            "Fixtures should have been written to ${outputDirectory.absolutePath}",
            File(outputDirectory, MANIFEST_NAME).exists()
        )
    }

    private data class Case(
        val fileName: String,
        val testType: TestType,
        val frames: List<PoseFrame>,
        val athleteHeightCm: Double? = null
    )

    /**
     * Deliberately spans the awkward cases, not just the happy path. Parity on
     * a clean five-rep sequence proves little; parity on partial reps, rejected
     * fast reps and lost tracking is where the two implementations would
     * actually diverge.
     */
    private fun cases(): List<Case> {

        val interval = PoseFixtures.DEFAULT_FRAME_INTERVAL_MS

        fun situpRun(
            repCount: Int,
            ascentFrames: Int,
            topAngle: Double = 55.0
        ): List<PoseFrame> {
            val frames = mutableListOf<PoseFrame>()
            frames += PoseFixtures.hold(0, 155.0, 10)
            var cursor = 10 * interval
            repeat(repCount) {
                val rep = PoseFixtures.sitUpRep(
                    startMs = cursor,
                    ascentFrames = ascentFrames,
                    descentFrames = ascentFrames,
                    topAngle = topAngle
                )
                frames += rep
                cursor = rep.last().timestampMs + interval
                frames += PoseFixtures.hold(cursor, 155.0, 8)
                cursor += 8 * interval
            }
            return frames
        }

        fun jumpRun(peakCm: Double, heightCm: Double): List<PoseFrame> {
            val frames = mutableListOf<PoseFrame>()
            val standing = PoseFixtures.standing(0)
            frames += standing
            var cursor = standing.last().timestampMs + interval
            val arc = PoseFixtures.jumpArc(cursor, peakCm, heightCm)
            frames += arc
            cursor = arc.last().timestampMs + interval
            frames += PoseFixtures.standing(cursor, frameCount = 10)
            return frames
        }

        val partialRepRun = mutableListOf<PoseFrame>().apply {
            this += PoseFixtures.hold(0, 155.0, 10)
            var cursor = 10 * interval
            // One clean rep, then one that stops short of the UP threshold.
            val clean = PoseFixtures.sitUpRep(cursor, 40, 40)
            this += clean
            cursor = clean.last().timestampMs + interval
            this += PoseFixtures.hold(cursor, 155.0, 8)
            cursor += 8 * interval
            this += PoseFixtures.sweep(cursor, 155.0, 95.0, 40)
            cursor += 40 * interval
            this += PoseFixtures.sweep(cursor, 95.0, 155.0, 40)
            cursor += 40 * interval
            this += PoseFixtures.hold(cursor, 155.0, 10)
        }

        val trackingLossRun = mutableListOf<PoseFrame>().apply {
            this += PoseFixtures.hold(0, 155.0, 10)
            var cursor = 10 * interval
            repeat(30) {
                this += PoseFixtures.occludedFrame(cursor)
                cursor += interval
            }
            val rep = PoseFixtures.sitUpRep(cursor, 40, 40)
            this += rep
            cursor = rep.last().timestampMs + interval
            this += PoseFixtures.hold(cursor, 155.0, 10)
        }

        return listOf(
            Case("situps_5_clean.csv", TestType.SIT_UPS, situpRun(5, 40)),
            Case("situps_10_fast.csv", TestType.SIT_UPS, situpRun(10, 20)),
            Case("situps_3_slow.csv", TestType.SIT_UPS, situpRun(3, 60)),
            Case("situps_partial_rep.csv", TestType.SIT_UPS, partialRepRun),
            Case("situps_tracking_loss.csv", TestType.SIT_UPS, trackingLossRun),
            Case(
                "situps_shallow_top_angle.csv",
                TestType.SIT_UPS,
                situpRun(4, 40, topAngle = 68.0)
            ),
            Case(
                "jump_40cm.csv",
                TestType.VERTICAL_JUMP,
                jumpRun(40.0, 170.0),
                athleteHeightCm = 170.0
            ),
            Case(
                "jump_15cm.csv",
                TestType.VERTICAL_JUMP,
                jumpRun(15.0, 170.0),
                athleteHeightCm = 170.0
            ),
            Case(
                "jump_60cm_tall.csv",
                TestType.VERTICAL_JUMP,
                jumpRun(60.0, 190.0),
                athleteHeightCm = 190.0
            ),
            Case(
                "jump_none.csv",
                TestType.VERTICAL_JUMP,
                PoseFixtures.standing(0, frameCount = 60),
                athleteHeightCm = 170.0
            )
        )
    }

    private fun format(value: Double): String =
        String.format(Locale.US, "%.4f", value)

    companion object {
        /** Relative to the Gradle module directory (mobile/app). */
        private const val FIXTURE_DIRECTORY = "../../backend/tests/fixtures/parity"
        private const val MANIFEST_NAME = "expected_scores.csv"
    }
}
