package com.sai.sports.analyzer

import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File
import java.util.Locale

/**
 * Exports canonical pose sequences plus the scores this implementation produces
 * for them, for the backend's parity test to check itself against.
 *
 * ## Why this exists
 *
 * The server auto-flags a submission when its score disagrees with the device's.
 * That mechanism is what makes results trustworthy — and it is also what breaks
 * first if the Kotlin and Python scorers drift apart. When they drift, the flag
 * fires on honest athletes, and the reviewer looking at the flag has no way to
 * tell a real discrepancy from an implementation gap.
 *
 * Two implementations of the same algorithm in two languages will drift. The
 * only question is whether anyone finds out before an athlete does. So this
 * test writes the sequences and the expected answers to a shared directory, and
 * `backend/tests/test_parity.py` asserts the Python port agrees.
 *
 * Fixtures are committed, so the backend suite does not depend on a Gradle run.
 * Regenerate after any threshold or algorithm change:
 *
 *     gradlew :app:testDebugUnitTest --tests "*ParityFixtureExportTest*"
 */
class ParityFixtureExportTest {

    private val outputDirectory = File(FIXTURE_DIRECTORY)

    @Test
    fun `export canonical fixtures and expected scores`() {

        outputDirectory.mkdirs()

        val manifest = StringBuilder()
        manifest.append("# Generated by ParityFixtureExportTest.kt — do not edit by hand.\n")
        manifest.append("# The backend's test_parity.py asserts the Python port reproduces these.\n")
        manifest.append("sequence,test,athlete_height_cm,expected_score,expected_status,expected_events\n")

        cases().forEach { case ->

            File(outputDirectory, case.fileName).writeText(
                PoseSequenceCodec.encode(case.frames, case.testType.displayName)
            )

            val analyzer = analyzerFor(case.testType, case.athleteHeightCm)

            val result = analyzer.analyzeSequence(case.frames)

            manifest.append(case.fileName).append(',')
            manifest.append(case.testType.name).append(',')
            manifest.append(case.athleteHeightCm?.let { format(it) } ?: "").append(',')
            manifest.append(format(result.score)).append(',')
            manifest.append(result.status.name).append(',')
            manifest.append(eventCounts(result)).append('\n')
        }

        File(outputDirectory, MANIFEST_NAME).writeText(manifest.toString())

        assertTrue(
            "Fixtures should have been written to ${outputDirectory.absolutePath}",
            File(outputDirectory, MANIFEST_NAME).exists()
        )
    }

    /**
     * How many times each outcome fired, e.g. `rep_counted=3;rep_rejected_partial=1;...`.
     * Equal scores can hide disagreement about *why* reps were refused — and the
     * reason is what the athlete and the reviewer are shown.
     */
    private fun eventCounts(result: AnalyzerResult): String {

        val labels = COMPARED_EVENTS.map { label ->
            "$label=${result.events.count { it.label == label }}"
        }

        // Which fault, not just how many: `issue.hips_sagging=3`. Counted
        // across rejections and warnings, so both implementations must agree
        // on what they told the athlete was wrong.
        val faultCodes = result.events
            .filter { it.label == "rep_rejected_form" || it.label == "form_warning" }
            .flatMap { it.detail.split(",") }
        val issues = FormIssue.entries.map { issue ->
            "issue.${issue.code}=${faultCodes.count { it == issue.code }}"
        }

        return (labels + issues).joinToString(";")
    }

    private data class Case(
        val fileName: String,
        val testType: TestType,
        val frames: List<PoseFrame>,
        val athleteHeightCm: Double? = null
    )

    /**
     * Deliberately spans the awkward cases, not just the happy path. Parity on
     * a clean five-rep sequence proves little; parity on partial reps, rejected
     * fast reps and lost tracking is where the two implementations would
     * actually diverge.
     */
    private fun cases(): List<Case> {

        val interval = PoseFixtures.DEFAULT_FRAME_INTERVAL_MS

        fun situpRun(
            repCount: Int,
            ascentFrames: Int,
            topAngle: Double = 55.0
        ): List<PoseFrame> {
            val frames = mutableListOf<PoseFrame>()
            frames += PoseFixtures.hold(0, 155.0, 10)
            var cursor = 10 * interval
            repeat(repCount) {
                val rep = PoseFixtures.sitUpRep(
                    startMs = cursor,
                    ascentFrames = ascentFrames,
                    descentFrames = ascentFrames,
                    topAngle = topAngle
                )
                frames += rep
                cursor = rep.last().timestampMs + interval
                frames += PoseFixtures.hold(cursor, 155.0, 8)
                cursor += 8 * interval
            }
            return frames
        }

        fun jumpRun(peakCm: Double, heightCm: Double): List<PoseFrame> {
            val frames = mutableListOf<PoseFrame>()
            val standing = PoseFixtures.standing(0)
            frames += standing
            var cursor = standing.last().timestampMs + interval
            val arc = PoseFixtures.jumpArc(cursor, peakCm, heightCm)
            frames += arc
            cursor = arc.last().timestampMs + interval
            frames += PoseFixtures.standing(cursor, frameCount = 10)
            return frames
        }

        val partialRepRun = mutableListOf<PoseFrame>().apply {
            this += PoseFixtures.hold(0, 155.0, 10)
            var cursor = 10 * interval
            // One clean rep, then one that stops short of the UP threshold.
            val clean = PoseFixtures.sitUpRep(cursor, 40, 40)
            this += clean
            cursor = clean.last().timestampMs + interval
            this += PoseFixtures.hold(cursor, 155.0, 8)
            cursor += 8 * interval
            this += PoseFixtures.sweep(cursor, 155.0, 95.0, 40)
            cursor += 40 * interval
            this += PoseFixtures.sweep(cursor, 95.0, 155.0, 40)
            cursor += 40 * interval
            this += PoseFixtures.hold(cursor, 155.0, 10)
        }

        val trackingLossRun = mutableListOf<PoseFrame>().apply {
            this += PoseFixtures.hold(0, 155.0, 10)
            var cursor = 10 * interval
            repeat(30) {
                this += PoseFixtures.occludedFrame(cursor)
                cursor += interval
            }
            val rep = PoseFixtures.sitUpRep(cursor, 40, 40)
            this += rep
            cursor = rep.last().timestampMs + interval
            this += PoseFixtures.hold(cursor, 155.0, 10)
        }

        return listOf(
            Case("situps_5_clean.csv", TestType.SIT_UPS, situpRun(5, 40)),
            Case("situps_10_fast.csv", TestType.SIT_UPS, situpRun(10, 20)),
            Case("situps_3_slow.csv", TestType.SIT_UPS, situpRun(3, 60)),
            Case("situps_partial_rep.csv", TestType.SIT_UPS, partialRepRun),
            Case("situps_tracking_loss.csv", TestType.SIT_UPS, trackingLossRun),
            Case(
                "situps_shallow_top_angle.csv",
                TestType.SIT_UPS,
                situpRun(4, 40, topAngle = 68.0)
            ),
            Case(
                "jump_40cm.csv",
                TestType.VERTICAL_JUMP,
                jumpRun(40.0, 170.0),
                athleteHeightCm = 170.0
            ),
            Case(
                "jump_15cm.csv",
                TestType.VERTICAL_JUMP,
                jumpRun(15.0, 170.0),
                athleteHeightCm = 170.0
            ),
            Case(
                "jump_60cm_tall.csv",
                TestType.VERTICAL_JUMP,
                jumpRun(60.0, 190.0),
                athleteHeightCm = 190.0
            ),
            Case(
                "jump_none.csv",
                TestType.VERTICAL_JUMP,
                PoseFixtures.standing(0, frameCount = 60),
                athleteHeightCm = 170.0
            )
        ) + repCases()
    }

    /** Squat, push-up, bicep curl and lunge — clean runs plus every rejection rule. */
    private fun repCases(): List<Case> {

        fun followedBy(first: List<PoseFrame>, second: List<PoseFrame>): List<PoseFrame> {
            val offset = first.last().timestampMs + RepFixtures.INTERVAL - second.first().timestampMs
            return first + second.map { it.copy(timestampMs = it.timestampMs + offset) }
        }

        val squatTrackingLoss = followedBy(
            RepFixtures.then(RepFixtures.run(2, RepFixtures.squat())) { RepFixtures.occluded(it, 20) },
            RepFixtures.run(2, RepFixtures.squat())
        )

        val pushUpsThenStanding = followedBy(
            RepFixtures.run(2, RepFixtures.pushUp()),
            RepFixtures.run(2, RepFixtures.pushUp(standing = true), startFrames = 0)
        )

        val curlsThenWrongArm = followedBy(
            RepFixtures.run(2, RepFixtures.curl(right = true)),
            RepFixtures.run(3, RepFixtures.curl(left = true, right = false), startFrames = 0)
        )

        return listOf(
            Case("squats_5_clean.csv", TestType.SQUATS, RepFixtures.run(5, RepFixtures.squat())),
            Case("squats_partial_rep.csv", TestType.SQUATS, RepFixtures.run(3, RepFixtures.squat(bottomAngle = 120.0))),
            Case("squats_fast.csv", TestType.SQUATS, RepFixtures.run(3, RepFixtures.squat(), downFrames = 3, upFrames = 3)),
            Case("squats_torso_lean.csv", TestType.SQUATS, RepFixtures.run(3, RepFixtures.squat(maxLean = 70.0))),
            Case("squats_far_side_hidden.csv", TestType.SQUATS, RepFixtures.run(4, RepFixtures.squat(farSideVisibility = 0.2f))),
            Case("squats_tracking_loss.csv", TestType.SQUATS, squatTrackingLoss),
            Case("squats_knee_past_toes.csv", TestType.SQUATS, RepFixtures.run(3, RepFixtures.squat(maxShinTilt = 40.0))),
            Case("squats_feet_moved.csv", TestType.SQUATS, RepFixtures.run(2, RepFixtures.squat(maxAnkleShift = 0.15))),
            Case(
                "squats_no_start.csv",
                TestType.SQUATS,
                RepFixtures.hold(0, 40, RepFixtures.squat(bottomAngle = 120.0), progress = 1.0)
            ),
            Case("pushups_4_clean.csv", TestType.PUSH_UPS, RepFixtures.run(4, RepFixtures.pushUp())),
            Case("pushups_sagging_hips.csv", TestType.PUSH_UPS, RepFixtures.run(3, RepFixtures.pushUp(hipOffset = 0.1))),
            Case("pushups_piked_hips.csv", TestType.PUSH_UPS, RepFixtures.run(2, RepFixtures.pushUp(hipOffset = -0.1))),
            Case("pushups_partial_rep.csv", TestType.PUSH_UPS, RepFixtures.run(2, RepFixtures.pushUp(bottomAngle = 115.0))),
            Case("pushups_then_standing.csv", TestType.PUSH_UPS, pushUpsThenStanding),
            Case("pushups_standing_only.csv", TestType.PUSH_UPS, RepFixtures.run(3, RepFixtures.pushUp(standing = true))),
            Case("curls_4_right_arm.csv", TestType.BICEP_CURLS, RepFixtures.run(4, RepFixtures.curl(right = true))),
            Case("curls_two_arm.csv", TestType.BICEP_CURLS, RepFixtures.run(3, RepFixtures.curl(left = true, right = true))),
            Case("curls_wrong_arm.csv", TestType.BICEP_CURLS, curlsThenWrongArm),
            Case("curls_elbow_flare.csv", TestType.BICEP_CURLS, RepFixtures.run(3, RepFixtures.curl(right = true, flare = 50.0))),
            Case("curls_body_swing.csv", TestType.BICEP_CURLS, RepFixtures.run(3, RepFixtures.curl(right = true, maxSway = 0.08))),
            Case("lunges_torso_lean.csv", TestType.LUNGES, RepFixtures.run(2, RepFixtures.lunge(maxTorsoLean = 45.0))),
            Case("curls_partial_rep.csv", TestType.BICEP_CURLS, RepFixtures.run(2, RepFixtures.curl(right = true, topAngle = 85.0))),
            Case("lunges_4_clean.csv", TestType.LUNGES, RepFixtures.run(4, RepFixtures.lunge())),
            Case("lunges_feet_together.csv", TestType.LUNGES, RepFixtures.run(3, RepFixtures.lunge(feetTogether = true))),
            Case(
                "lunges_knee_past_toes.csv",
                TestType.LUNGES,
                RepFixtures.run(2, RepFixtures.lunge(frontHipAtBottom = 80.0, frontKneeAtBottom = 70.0))
            ),
            Case(
                "lunges_partial_rep.csv",
                TestType.LUNGES,
                RepFixtures.run(
                    2,
                    RepFixtures.lunge(frontHipAtBottom = 50.0, frontKneeAtBottom = 125.0, backKneeAtBottom = 130.0)
                )
            )
        )
    }

    private fun format(value: Double): String =
        String.format(Locale.US, "%.4f", value)

    companion object {
        /** Relative to the Gradle module directory (mobile/app). */
        private const val FIXTURE_DIRECTORY = "../../backend/tests/fixtures/parity"
        private const val MANIFEST_NAME = "expected_scores.csv"

        private val COMPARED_EVENTS = listOf(
            "rep_counted",
            "rep_rejected_partial",
            "rep_rejected_too_fast",
            "rep_rejected_form",
            "rep_rejected_wrong_arm",
            "form_warning",
            "tracking_lost"
        )
    }
}
