"""initial schema

Revision ID: 3cc2fab51ed5
Revises: 
Create Date: 2026-08-27 08:53:44.249562
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = '3cc2fab51ed5'
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athletes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='gender', native_enum=False, length=20), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('height_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('reference_face_key', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("gender IN ('male','female','other')", name='ck_athletes_gender'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('officials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('role', sa.Enum('sai_admin', 'regional_reviewer', name='officialrole', native_enum=False, length=30), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('tests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('benchmarks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('test_id', sa.Uuid(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('age_min', sa.Integer(), nullable=False),
    sa.Column('age_max', sa.Integer(), nullable=False),
    sa.Column('percentile_50', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('percentile_75', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('percentile_90', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('athlete_id', sa.Uuid(), nullable=False),
    sa.Column('test_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('provisional_score', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('server_score', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('final_score', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('pending_sync', 'processing', 'verified', 'flagged', 'approved', 'rejected', name='testresultstatus', native_enum=False, length=30), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending_sync','processing','verified','flagged','approved','rejected')", name='ck_test_results_status'),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_id', 'test_id', 'attempt_number', name='uq_result_attempt')
    )
    op.create_index('ix_test_results_status', 'test_results', ['status'], unique=False)
    op.create_table('face_verifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('test_result_id', sa.Uuid(), nullable=False),
    sa.Column('verification_status', sa.Enum('pass', 'fail', 'manual_review', name='faceverificationstatus', native_enum=False, length=20), nullable=False),
    sa.Column('similarity_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['test_result_id'], ['test_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('test_result_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.Enum('auto', 'manual', name='flagsource', native_enum=False, length=20), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', name='flagseverity', native_enum=False, length=20), nullable=False),
    sa.Column('resolved_by', sa.Uuid(), nullable=True),
    sa.Column('resolution', sa.Enum('confirmed', 'dismissed', name='flagresolution', native_enum=False, length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['resolved_by'], ['officials.id'], ),
    sa.ForeignKeyConstraint(['test_result_id'], ['test_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_flags_test_result', 'flags', ['test_result_id'], unique=False)
    op.create_table('review_actions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('test_result_id', sa.Uuid(), nullable=False),
    sa.Column('official_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.Enum('approved', 'rejected', 'requested_resubmission', name='reviewaction', native_enum=False, length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['official_id'], ['officials.id'], ),
    sa.ForeignKeyConstraint(['test_result_id'], ['test_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('videos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('test_result_id', sa.Uuid(), nullable=True),
    sa.Column('s3_key', sa.String(length=500), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('duration_seconds', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sensor_telemetry_key', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['test_result_id'], ['test_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_videos_test_result', 'videos', ['test_result_id'], unique=False)
    op.create_table('upload_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('athlete_id', sa.Uuid(), nullable=True),
    sa.Column('test_code', sa.String(length=40), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('chunk_size_bytes', sa.Integer(), nullable=False),
    sa.Column('total_chunks', sa.Integer(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('received_chunks', sa.Text(), nullable=False),
    sa.Column('staging_path', sa.String(length=500), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('video_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upload_sessions')
    op.drop_index('ix_videos_test_result', table_name='videos')
    op.drop_table('videos')
    op.drop_table('review_actions')
    op.drop_index('ix_flags_test_result', table_name='flags')
    op.drop_table('flags')
    op.drop_table('face_verifications')
    op.drop_index('ix_test_results_status', table_name='test_results')
    op.drop_table('test_results')
    op.drop_table('benchmarks')
    op.drop_table('tests')
    op.drop_table('officials')
    op.drop_table('athletes')
    # ### end Alembic commands ###
